query getUserChats {
  getUserChats {
    id
    title
    type
    messages(sort: { orderBy: desc, take: 1 }) {
      message
      senderId
      sender {
        login
      }
    }
    chatParticipants(withUser: false) {
      login
    }
  }
}
